version: '3.7'

services:

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: elasticsearch:1.7.6-alpine
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.ping.unicast.hosts=127.0.0.1
     
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-config:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticnet3

  augmenterservice:
    build: .
    restart: always
    container_name: augmenterservice
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - SURVEYINTERLINK_URL=${SURVEYINTERLINK_URL}
      - SURVEYAPI_VERSION=${SURVEYAPI_VERSION}
    depends_on:
      - elasticsearch
    networks:
      - elasticnet3

volumes:
  elasticsearch-data:
    driver: local
  elasticsearch-config:
    driver: local


networks:
  elasticnet3:
    # Use a custom driver
    driver: bridge
  