openapi: 3.0.1

info:
  title: Annotator Interlinker
  description: 'This API allows to create Annotations of Public Services Descriptions'
  termsOfService: http://interlink-project.eu/terms/
  contact:
    email: d.silva@deusto.es
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1'

servers:
  - url: http://127.0.0.1:5000/
    description: Annotation made in a web document
tags:
- name: annotations
  description: Everything about your Annotations
 
paths:
  /annotations:
    get:
      tags:
        - annotations
      description: List all the annotations registered
      summary: List Annotations
      operationId: getAnnotations

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Annotation'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Annotation'
        '400':
          description: Invalid status value
    parameters:
      - in: query
        name: offset
        schema:
          type: integer
        description: The number of items to skip before starting to collect the result set
      - in: query
        name: limit
        schema:
          type: integer
        description: The numbers of items to return
  

    
components:
  schemas:
    Annotation:
      type: object
      properties:
        section_title:
          type: string
        ranges:
          type: object
          properties:
            endOffset: 
                type: integer
            startOffset: 
                type: integer
            start: 
                type: string
            end:
                type: string
        created:
          type: string
          format: date-time
        section:
          type: string
        uri:
          type: string
        quote:
          type: string
        permissions:
          type: object
          properties:
            read:
                type: string
            update:
                type: string
            admin:
                type: string
            delete:
                type: string
        data_creacio:
          type: string
        text:
          type: string
        category:
          type: string
        user:
          type: string
        updated:
          type: string
          format: date-time
        consumer:
          type: string
        order:
          type: string
        id:
          type: string